### ISSUE TITLE
Desafio 50: Acessando Servidor Remoto

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#57]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Em construção

### Additional tips

Docker compose base

```
version: "3"

services:
    app:
        build: ./docker/php
        container_name: app
        restart: always
        tty: true
        volumes:
            - ./app:/var/www/html/app
            - ./.env:/var/www/html/.env
            - ./app/src/storage/sessions:/var/www/html/app/src/storage/sessions
            - ./docker/php/php_errors.log:/usr/share/nginx/html/php_errors.log
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        ports:
            - ${APP_PORT}:9000
        networks:
            - rede

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        tty: true
        volumes:
            - ./app:/var/www/html/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        networks:
            - rede

networks:
    rede:
        driver: bridge
```
